# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration for Dockerfile files"

on:
  pull_request:
    paths:
      - ".docker/**/*"
      - ".github/workflows/ci-dockerfile.yml"
  push:
    branches:
      - "*.*.x"
    paths:
      - ".docker/**/*"
      - ".github/workflows/ci-dockerfile.yml"
  schedule:
    - cron: "0 17 * * *"

jobs:
  lint-dockerfile:
    name: "Lint Dockerfile files with Hadolint"
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Lint Dockerfile"
        uses: "hadolint/hadolint-action@v3.1.0"
        with:
          dockerfile: ".docker/validate-against-schema/Dockerfile"
